# Generated by Django 5.0.6 on 2024-05-20 12:18

import app.models
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='إسم المقال:')),
                ('img', models.ImageField(upload_to=app.models.image_upload_cat, verbose_name='الصورة:')),
                ('details', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='الوصف')),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='إسم المنتج:')),
                ('price', models.IntegerField(verbose_name='السعر')),
                ('img1', models.ImageField(upload_to=app.models.image_upload, verbose_name='الصورة الرئيسية')),
                ('img2', models.ImageField(blank=True, null=True, upload_to=app.models.image_upload, verbose_name='الصورة2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to=app.models.image_upload, verbose_name='الصورة3')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
