# Generated by Django 5.0.6 on 2024-05-20 12:35

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='إسمك الكامل')),
                ('phone', models.IntegerField(verbose_name='رقم الهاتف')),
                ('state', models.CharField(choices=[('الشلف', 'الشلف'), ('الجزائر', 'الجزائر'), ('عين الدفلى', 'عين الدفلى')], max_length=50, verbose_name='الولاية')),
                ('city', models.CharField(max_length=50, verbose_name='البلدية')),
                ('order_at', models.DateTimeField(auto_now=True, verbose_name='وقت نشر الطلبية')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='الكمية')),
                ('status', models.CharField(blank=True, choices=[('delivered', 'تم التسليم'), ('confirmed', 'تم التأكيد'), ('canceled', 'ملغي'), ('in_progress', 'جاري التوصيل'), ('changed', 'تم تغيير الطلبية')], max_length=50, null=True, verbose_name='الحالة')),
                ('delivery', models.CharField(blank=True, choices=[('stop_desk', 'المكتب'), ('home', 'المنزل')], max_length=50, null=True, verbose_name='نوع التوصيل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_order', to='app.product', verbose_name='إسم المنتج')),
            ],
        ),
    ]
