# Generated by Django 5.0.6 on 2024-05-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_active_product_active_product_details_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='name',
        ),
    ]
