# Generated by Django 5.0.6 on 2024-05-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_title_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=1, max_length=50, verbose_name='إسم الكاتب:'),
            preserve_default=False,
        ),
    ]
